"""DP-02: the dynamic module generated by for_root_async and register_async carries providers and
exports only, so the factory's inject list cannot name anything the importing module provides and
there is no way to give the registration an import of its own.
"""

from bustan import (
    ConfigurableModuleBuilder,
    Injectable,
    Module,
    create_app_context,
)
from bustan.errors import BustanError


@Injectable()
class HostConfig:
    url = "redis://host"


@Module(providers=[HostConfig], exports=[HostConfig])
class HostModule:
    pass


def build_options(config: HostConfig) -> dict[str, str]:
    return {"url": config.url}


def main() -> None:
    cache_module, options_token = ConfigurableModuleBuilder().set_class_name("CacheModule").build()

    try:
        registration = cache_module.for_root_async(
            use_factory=build_options,
            inject=(HostConfig,),
            imports=(HostModule,),
        )
    except TypeError as exc:
        print(f"RESULT: DP-02 REPRODUCED - the async builder takes no 'imports': {exc}")
        return

    @Module(imports=[registration])
    class AppModule:
        pass

    try:
        resolved = create_app_context(AppModule).get(options_token)
    except BustanError as exc:
        print(f"RESULT: DP-02 REPRODUCED - {type(exc).__name__}: {exc}")
        return

    if resolved == {"url": "redis://host"}:
        print(
            "RESULT: DP-02 FIXED - for_root_async took an 'imports' and its factory resolved "
            f"HostConfig from the imported module: {resolved}"
        )
        return
    print(f"RESULT: DP-02 REPRODUCED - the factory answered with {resolved!r}")


if __name__ == "__main__":
    main()
