#!/usr/bin/env python3
"""Check an issue, pull request or comment against the programme's writing rules.

Everything the programme posts is read later by a person who was not there, so a
title, a body and every comment are held to the shape in references/WRITING.md: a
one-clause title without ticket ids, a body inside its word budget with verification
reported as one line per command, the ticket's acceptance criteria ticked one box each
with their evidence, and nothing addressed to the agent or the reviewer as a person. An
issue must hang under a parent unless it is the epic itself. This reports every rule a
writeup breaks and exits non-zero when there is at least one. The supervisor runs it
before dispatching an issue and before reading a pull request; an agent runs it on a
draft body before opening the pull request.

The text comes from GitHub (--issue or --pr, with a token in GH_TOKEN or GITHUB_TOKEN)
or from a local file (--file, which needs --kind; --issue-body gives the ticket a draft
pull request is checked against). The budgets are the defaults WRITING.md documents and
move with the --max-* flags.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any, NamedTuple, cast

import check_ownership

TITLE_LIMIT = 72
ISSUE_WORD_LIMIT = 400
PR_WORD_LIMIT = 300
VERIFICATION_LINE_LIMIT = 12
ACCEPTANCE_ITEM_LIMIT = 12
FENCED_LINE_LIMIT = 20
BODY_CHAR_LIMIT = 10_000
REVIEW_WORD_LIMIT = 150
COMMENT_WORD_LIMIT = 60
# A criterion is recognised by this many characters of its normalised text, so a box
# has to quote the issue rather than paraphrase it, and a short criterion still matches.
CRITERION_PREFIX = 60
EPIC_LABEL = "epic"

TICKET_ID = re.compile(r"\bT-\d{3}\b")
FINDING_ID = re.compile(r"\b(?:CR|DP|EX|MG|OL|PN|QA|RF|RI)-\d{2}\b")
SERIES_PREFIX = re.compile(r"^[A-Z][A-Za-z]+ [A-Z0-9]{1,2}:\s")
FOOTER = re.compile(
    r"Generated by \[Claude Code\]|claude\.ai/code|session_[0-9A-Za-z]{16,}"
    r"|Co-Authored-By:|Claude-Session:",
    re.IGNORECASE,
)
CHECKBOX = re.compile(r"^\s*[-*] \[([ xX])\] (.*)$")
MARKUP = re.compile(r"[*`]")
# A lone capital I followed by punctuation or a space, but not the I in I/O.
FIRST_PERSON = re.compile(r"(?<![\w/])I(?=[\s,.;:'!?]|$)")
SECOND_PERSON = re.compile(r"\b(?:you|your|yours)\b", re.IGNORECASE)
CLOSES = re.compile(r"\bCloses #(\d+)")
CLOSES_IN_CODE = re.compile(r"`[^`\n]*\bCloses #\d+[^`\n]*`")
CODE_SPAN = re.compile(r"`[^`\n]*`")
HEADING = re.compile(r"^#{1,6}\s+(.+?)\s*$")
LEAD_IN = re.compile(r"^\*\*([^*]+?)\*\*")
FENCE = re.compile(r"^(?:```|~~~)")
BULLET = re.compile(r"^\s*[-*] ")
DRAFT_FIRST_LINES = ("BLOCKED:", "DECISION REQUIRED:")

# Substrings that only ever appear when the writer is talking to the other agent, to
# itself, or about its tooling. Matched case-insensitively against every line.
BANNED_PHRASES = (
    "I want to be",
    "I was wrong",
    "I got wrong",
    "Correcting my",
    "Correcting the",
    "I said I would",
    "you caught",
    "beat my grep",
    "deserved better",
    "Nothing arrived outside",
    "Every acceptance criterion is met",
    "nothing outside Owns",
    "both granted paths are used",
    "Supervisor amendment",
    "as a finding rather than acted on",
    "Read this section before anything else",
    "yours to create",
    "pasted verbatim",
    "GraphQL is not served",
    "only the pinned set",
    "this session",
    "I cannot undraft",
)
# Section names, as a heading or a bold lead-in, that carry programme chatter rather
# than the work: rules repeated from the backlog, pasted output, or a confession.
BANNED_HEADINGS = (
    "Working agreement",
    "Verification block",
    "Files touched",
    "Note on how this work was directed",
    "Decisions where more than one option was defensible",
    "What was deliberately not done",
    "What I verified",
    "Two things I got wrong",
)
# Banned only as a bold lead-in: an epic body legitimately carries a Sequencing table,
# but a ticket that says "Sequencing." is publishing scheduler state as prose.
BANNED_LEAD_INS = ("Sequencing",)
EXCLUDED_SECTIONS = {
    "issue": ("owns", "must not touch"),
    "pr": ("verification", "acceptance"),
}
VERDICTS = {
    "issue": "The issue goes back before it is dispatched.",
    "pr": "The writeup goes back before the diff is read.",
    "comment": "The comment is edited before it is posted.",
}


class Finding(NamedTuple):
    """One rule's result: `ok`, `WARN`, or `FAIL`, with what was measured."""

    level: str
    check: str
    detail: str


class Limits(NamedTuple):
    """The budgets one body is measured against."""

    title: int
    words: int
    verification_lines: int
    fenced_lines: int
    chars: int
    acceptance_items: int = ACCEPTANCE_ITEM_LIMIT


class Item(NamedTuple):
    """One box under a pull request's Acceptance: its line, its state and its text."""

    line: int
    ticked: bool
    text: str


class Segments(NamedTuple):
    """The parts of a body each rule reads, split once."""

    prose: list[tuple[int, str]]
    headings: list[tuple[int, str, bool]]
    fenced_lines: int
    verification_lines: int
    owns_has_details: bool
    acceptance: list[Item]
    acceptance_plain: list[int]
    stray_checkboxes: list[int]
    not_done: list[str]


def segment(body: str, excluded: tuple[str, ...], checkbox_section: str | None = None) -> Segments:
    """Split a body into prose, headings, checkboxes and the counts the budgets need.

    Prose leaves out fenced blocks, `<details>` blocks, HTML comments, table rows and
    every line under a heading named in `excluded`, so a word count measures what a
    reader has to read. Headings carry whether they were a bold lead-in. Checkboxes are
    boxes under `checkbox_section`, with a wrapped box's later lines joined to it; a box
    anywhere else is stray, and so is every box when no section may carry one.
    """
    prose: list[tuple[int, str]] = []
    headings: list[tuple[int, str, bool]] = []
    acceptance: list[Item] = []
    plain: list[int] = []
    stray: list[int] = []
    not_done: list[str] = []
    fenced = verification = 0
    owns_has_details = False
    in_fence = in_details = in_comment = False
    section = ""
    for number, line in enumerate(body.splitlines(), start=1):
        stripped = line.strip()
        if in_comment:
            in_comment = "-->" not in stripped
            continue
        if stripped.startswith("<!--"):
            in_comment = "-->" not in stripped[4:]
            continue
        if FENCE.match(stripped):
            in_fence = not in_fence
            continue
        if in_fence:
            fenced += 0 if in_details else 1
            continue
        lowered = stripped.lower()
        if lowered.startswith("<details"):
            in_details = True
            owns_has_details = owns_has_details or section == "owns"
            continue
        if lowered.startswith("</details"):
            in_details = False
            continue
        if in_details:
            continue
        match = HEADING.match(stripped) or LEAD_IN.match(stripped)
        if match:
            text = match.group(1).strip().rstrip(".:")
            headings.append((number, text, not stripped.startswith("#")))
            section = text.lower()
            rest = stripped[match.end() :].strip()
            if rest and section not in excluded:
                prose.append((number, rest))
            continue
        checkbox = CHECKBOX.match(line)
        if checkbox:
            if section == checkbox_section:
                acceptance.append(Item(number, checkbox.group(1) != " ", checkbox.group(2).strip()))
            else:
                stray.append(number)
        elif section == checkbox_section and stripped:
            if acceptance and (line[:1].isspace() or not BULLET.match(line)):
                last = acceptance[-1]
                acceptance[-1] = last._replace(text=f"{last.text} {stripped}")
            else:
                plain.append(number)
        if section == "not done" and stripped:
            not_done.append(stripped)
        if section == "verification" and BULLET.match(stripped):
            verification += 1
        if section in excluded or not stripped or stripped.startswith("|"):
            continue
        prose.append((number, line))
    return Segments(
        prose,
        headings,
        fenced,
        verification,
        owns_has_details,
        acceptance,
        plain,
        stray,
        not_done,
    )


def _verdict(
    check: str, passed: bool, detail: str, level: str = "FAIL", ok_detail: str | None = None
) -> Finding:
    if passed:
        return Finding("ok", check, detail if ok_detail is None else ok_detail)
    return Finding(level, check, detail)


def check_title(title: str, limit: int) -> list[Finding]:
    """Apply the title rules: one clause, under the cap, carrying no identifiers."""
    length = len(title)
    ticket = TICKET_ID.search(title)
    finding = FINDING_ID.search(title)
    series = SERIES_PREFIX.match(title)
    return [
        _verdict("title.length", length <= limit, f"{length} characters, limit {limit}"),
        _verdict("title.ticket-id", ticket is None, ticket.group(0) if ticket else "none"),
        _verdict("title.finding-id", finding is None, finding.group(0) if finding else "none"),
        _verdict(
            "title.series-prefix", series is None, series.group(0).strip() if series else "none"
        ),
        _verdict(
            "title.programme",
            "programme" not in title.lower(),
            "says 'programme'",
            ok_detail="no programme talk",
        ),
        _verdict(
            "title.trailing-period",
            not title.rstrip().endswith("."),
            "ends with a period",
            ok_detail="no trailing period",
        ),
    ]


def _word_count(prose: list[tuple[int, str]]) -> int:
    return sum(len(re.findall(r"\S+", text)) for _, text in prose)


def _line_hits(body: str, pattern: re.Pattern[str]) -> list[tuple[int, str]]:
    return [
        (number, match.group(0))
        for number, line in enumerate(body.splitlines(), start=1)
        if (match := pattern.search(line))
    ]


def _banned_phrases(body: str) -> list[Finding]:
    lines = body.lower().splitlines()
    hits = [
        (phrase, number)
        for phrase in BANNED_PHRASES
        for number, line in enumerate(lines, start=1)
        if phrase.lower() in line
    ]
    if not hits:
        return [Finding("ok", "body.banned", "no banned phrase")]
    return [
        Finding("FAIL", "body.banned", f'"{phrase}" (line {number})') for phrase, number in hits
    ]


def _banned_headings(headings: list[tuple[int, str, bool]]) -> list[Finding]:
    hits = []
    for number, text, is_lead_in in headings:
        lowered = text.lower()
        banned = [name for name in BANNED_HEADINGS if name.lower() in lowered]
        if is_lead_in:
            banned.extend(name for name in BANNED_LEAD_INS if lowered.startswith(name.lower()))
        hits.extend(f'"{text}" (line {number})' for _ in banned[:1])
    if not hits:
        return [Finding("ok", "body.banned-heading", "no banned section")]
    return [Finding("FAIL", "body.banned-heading", hit) for hit in hits]


def _footer(body: str) -> list[Finding]:
    hits = _line_hits(body, FOOTER)
    if not hits:
        return [Finding("ok", "body.footer", "no footer, session link or trailer")]
    return [Finding("FAIL", "body.footer", f"{text} (line {number})") for number, text in hits]


def _checkboxes(parts: Segments) -> Finding:
    if not parts.stray_checkboxes:
        return Finding("ok", "body.checkbox", "no checkbox outside Acceptance")
    shown = ", ".join(str(number) for number in parts.stray_checkboxes[:5])
    return Finding(
        "FAIL",
        "body.checkbox",
        f"{len(parts.stray_checkboxes)} checkboxes outside ## Acceptance (lines {shown})",
    )


def _non_ascii(body: str) -> Finding:
    for number, line in enumerate(body.splitlines(), start=1):
        if any(ord(character) > 127 for character in line):
            return Finding("FAIL", "body.non-ascii", f"line {number}: {line.strip()[:60]}")
    return Finding("ok", "body.non-ascii", "ASCII only")


def _person(prose: list[tuple[int, str]], pattern: re.Pattern[str]) -> int:
    return sum(
        len(pattern.findall(CODE_SPAN.sub(" ", text)))
        for _, text in prose
        if not text.lstrip().startswith(">")
    )


def _owns(body: str, parts: Segments) -> list[Finding]:
    findings = []
    try:
        patterns = check_ownership.owns_patterns_from_body(body, "this body")
    except check_ownership.GitHubError as error:
        findings.append(Finding("FAIL", "issue.owns", str(error)))
    else:
        findings.append(Finding("ok", "issue.owns", f"{len(patterns)} patterns parse"))
    if parts.owns_has_details:
        findings.append(Finding("FAIL", "issue.owns", "a <details> block inside the Owns section"))
    return findings


def _without_fences(body: str) -> str:
    kept = []
    in_fence = False
    for line in body.splitlines():
        if FENCE.match(line.strip()):
            in_fence = not in_fence
            continue
        if not in_fence:
            kept.append(line)
    return "\n".join(kept)


def _closed_issue(body: str) -> int | None:
    """The issue a live `Closes #N` line names, ignoring one inside code."""
    match = CLOSES.search(CODE_SPAN.sub(" ", _without_fences(body)))
    return int(match.group(1)) if match else None


def _closes(body: str, expected: int | None, no_issue: bool = False) -> Finding:
    number = _closed_issue(body)
    if number is None and CLOSES_IN_CODE.search(body):
        return Finding("FAIL", "pr.closes", "Closes #N is inside a code span, which GitHub ignores")
    if number is None and no_issue:
        return Finding("ok", "pr.closes", "no issue to close (--no-issue)")
    if number is None:
        return Finding("FAIL", "pr.closes", "no Closes #N line")
    if expected is not None and number != expected:
        return Finding("FAIL", "pr.closes", f"Closes #{number}, expected #{expected}")
    return Finding("ok", "pr.closes", f"Closes #{number} is a live closing keyword")


def _normalise(text: str) -> str:
    return " ".join(MARKUP.sub("", text).lower().split())


def _key(text: str) -> str:
    """The prefix a criterion is recognised by: normalised, cut, and shorn of punctuation."""
    return _normalise(text)[:CRITERION_PREFIX].rstrip(" .,:;")


def criteria(issue_body: str) -> list[str]:
    """The top-level bullets under the issue's Acceptance, each with its wrapped lines joined."""
    found: list[str] = []
    inside = False
    for line in issue_body.splitlines():
        stripped = line.strip()
        match = HEADING.match(stripped) or LEAD_IN.match(stripped)
        if match:
            inside = match.group(1).strip().rstrip(".:").lower() == "acceptance"
            continue
        if not inside or not stripped:
            continue
        if BULLET.match(line) and not line[:1].isspace():
            found.append(BULLET.sub("", line, count=1).strip())
        elif found:
            found[-1] = f"{found[-1]} {stripped}"
    return found


def _acceptance(
    parts: Segments, issue_body: str | None, limit: int, no_issue: bool
) -> list[Finding]:
    """Hold the pull request's Acceptance checklist to the issue's criteria.

    Every box must quote a criterion closely enough that its first characters match,
    every criterion must have a box, and an unticked box must be repeated under Not
    done, where its reason lives.
    """
    if no_issue:
        return [Finding("ok", "pr.acceptance", "no issue, so no criteria to list (--no-issue)")]
    if not any(text.lower() == "acceptance" for _, text, _ in parts.headings):
        return [Finding("FAIL", "pr.acceptance", "no ## Acceptance section")]
    findings = [
        Finding("FAIL", "pr.acceptance", f"line {number} under Acceptance is not a checkbox")
        for number in parts.acceptance_plain
    ]
    if len(parts.acceptance) > limit:
        findings.append(
            Finding("FAIL", "pr.acceptance", f"{len(parts.acceptance)} boxes, limit {limit}")
        )
    if issue_body is None:
        findings.append(
            Finding("WARN", "pr.acceptance", "no issue body, so the criteria were not compared")
        )
        return findings
    keys = [_key(criterion) for criterion in criteria(issue_body)]
    if not keys:
        findings.append(
            Finding("WARN", "pr.acceptance", "the issue has no Acceptance bullets to compare")
        )
        return findings
    texts = [_normalise(item.text) for item in parts.acceptance]
    matched = [next((key for key in keys if key in text), None) for text in texts]
    findings.extend(
        Finding("FAIL", "pr.acceptance", f'criterion not in the checklist: "{key}"')
        for key in keys
        if key not in matched
    )
    not_done = _normalise(" ".join(parts.not_done))
    for index, item in enumerate(parts.acceptance):
        key = matched[index] or _key(texts[index])
        if matched[index] is None:
            findings.append(
                Finding("WARN", "pr.acceptance", f"line {item.line} matches no criterion")
            )
        if not item.ticked and key not in not_done:
            findings.append(
                Finding("FAIL", "pr.acceptance", f'unticked but not under Not done: "{key}"')
            )
    if not any(finding.level == "FAIL" for finding in findings):
        unticked = sum(not item.ticked for item in parts.acceptance)
        findings.append(
            Finding(
                "ok",
                "pr.acceptance",
                f"{len(keys)} criteria in the checklist, {unticked} unticked and under Not done",
            )
        )
    return findings


def _parent(repo: str, number: int) -> dict[str, Any] | None:
    """The issue's parent, or None when GitHub answers 404 because there is none."""
    try:
        return _fetch_object(f"/repos/{repo}/issues/{number}/parent")
    except check_ownership.GitHubError as error:
        if " returned 404:" in str(error):
            return None
        raise


def check_parent(repo: str, number: int, epic: bool) -> Finding:
    """A ticket or follow-up hangs under an epic or the issue it came from; an epic alone stands."""
    if epic:
        return Finding("ok", "issue.parent", "an epic has no parent")
    parent = _parent(repo, number)
    if parent is None:
        return Finding(
            "FAIL",
            "issue.parent",
            f"no parent issue; attach one with: gh issue edit {number} --parent P",
        )
    title = str(parent.get("title", ""))[:50]
    return Finding("ok", "issue.parent", f"parent #{parent.get('number')}: {title}")


def check_body(
    kind: str,
    body: str,
    limits: Limits,
    *,
    draft: bool = False,
    closes: int | None = None,
    no_issue: bool = False,
    issue_body: str | None = None,
    epic: bool = False,
) -> list[Finding]:
    """Apply every body rule for `kind` (issue, pr or comment) and return the findings."""
    parts = segment(body, EXCLUDED_SECTIONS.get(kind, ()), "acceptance" if kind == "pr" else None)
    words = _word_count(parts.prose)
    findings = [
        _verdict("body.words", words <= limits.words, f"{words} words, limit {limits.words}"),
        _verdict(
            "body.fenced-lines",
            parts.fenced_lines <= limits.fenced_lines,
            f"{parts.fenced_lines} outside <details>, limit {limits.fenced_lines}",
        ),
        _verdict("body.chars", len(body) <= limits.chars, f"{len(body)}, limit {limits.chars}"),
        *_banned_phrases(body),
        *_banned_headings(parts.headings),
        *_footer(body),
        _checkboxes(parts),
        _non_ascii(body),
    ]
    first_person = _person(parts.prose, FIRST_PERSON)
    findings.append(
        _verdict(
            "body.first-person",
            first_person == 0,
            f"{first_person} first-person sentences",
            level="WARN" if kind == "comment" else "FAIL",
        )
    )
    if kind == "issue":
        second_person = _person(parts.prose, SECOND_PERSON)
        findings.append(
            _verdict("issue.second-person", second_person == 0, f"{second_person} addresses")
        )
        if epic:
            findings.append(Finding("ok", "issue.owns", "an epic owns no files"))
        else:
            findings.extend(_owns(body, parts))
    if kind == "pr":
        findings.append(_closes(body, closes, no_issue))
        findings.extend(_acceptance(parts, issue_body, limits.acceptance_items, no_issue))
        has_verification = any(text.lower() == "verification" for _, text, _ in parts.headings)
        findings.append(
            _verdict(
                "pr.verification",
                has_verification,
                "no ## Verification section",
                ok_detail="a Verification section is present",
            )
        )
        if has_verification:
            findings.append(
                _verdict(
                    "pr.verification",
                    parts.verification_lines <= limits.verification_lines,
                    f"{parts.verification_lines} lines, limit {limits.verification_lines}",
                )
            )
        has_not_done = any(text.lower() == "not done" for _, text, _ in parts.headings)
        findings.append(
            _verdict(
                "pr.not-done",
                has_not_done,
                "no ## Not done section",
                ok_detail="a Not done section is present",
            )
        )
        if draft:
            first = next((line for line in body.splitlines() if line.strip()), "")
            findings.append(
                _verdict(
                    "pr.draft",
                    first.startswith(DRAFT_FIRST_LINES),
                    "a draft that does not open with BLOCKED: or DECISION REQUIRED:",
                    level="WARN",
                    ok_detail="the draft opens with its protocol line",
                )
            )
    return findings


def _summary(label: str, title: str | None, body: str, kind: str) -> str:
    parts = segment(body, EXCLUDED_SECTIONS.get(kind, ()), "acceptance" if kind == "pr" else None)
    title_part = f"title {len(title)} chars" if title is not None else "no title given"
    return (
        f"writeup ({label}): {title_part}; body {len(body)} chars, "
        f"{_word_count(parts.prose)} words, {parts.fenced_lines} fenced lines"
    )


def _fetch_object(path: str) -> dict[str, Any]:
    """GET one JSON object, refusing anything else."""
    payload = check_ownership._get(path)
    if not isinstance(payload, dict):
        raise check_ownership.GitHubError(f"unexpected response from GET {path}")
    return cast("dict[str, Any]", payload)


def _fetch_list(path: str) -> list[dict[str, Any]]:
    """GET one JSON list of objects, refusing anything else."""
    payload = check_ownership._get(path)
    if not isinstance(payload, list):
        raise check_ownership.GitHubError(f"unexpected response from GET {path}")
    return cast("list[dict[str, Any]]", payload)


def _fetch_comments(repo: str, pull_number: int) -> list[tuple[str, str, str]]:
    """Return (label, kind, body) for every comment on the pull request not left by a bot."""
    sources = (
        ("review", f"/repos/{repo}/pulls/{pull_number}/reviews"),
        ("inline", f"/repos/{repo}/pulls/{pull_number}/comments"),
        ("comment", f"/repos/{repo}/issues/{pull_number}/comments"),
    )
    comments: list[tuple[str, str, str]] = []
    for kind, path in sources:
        for entry in _fetch_list(f"{path}?per_page=100"):
            author = str(entry.get("user", {}).get("login", ""))
            body = entry.get("body")
            if author.endswith("[bot]") or not body:
                continue
            comments.append((f"{kind} {entry.get('id')} by {author}", kind, str(body)))
    return comments


def _format(findings: list[Finding]) -> list[str]:
    return [f"{finding.level:<4}  {finding.check:<22}{finding.detail}" for finding in findings]


def _parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--issue", type=int, metavar="N", help="check issue N on --repo")
    source.add_argument("--pr", type=int, metavar="N", help="check pull request N on --repo")
    source.add_argument("--file", type=Path, metavar="BODY.md", help="check a body on disk")
    parser.add_argument("--repo", metavar="OWNER/REPO")
    parser.add_argument("--kind", choices=("issue", "pr", "comment"), help="required with --file")
    parser.add_argument("--title", help="the title to check alongside --file")
    parser.add_argument("--closes", type=int, metavar="M", help="the issue a PR must close")
    parser.add_argument(
        "--no-issue",
        action="store_true",
        help="the pull request closes no issue, so a missing Closes line is not a failure",
    )
    parser.add_argument(
        "--issue-body",
        type=Path,
        metavar="ISSUE.md",
        help="with --file --kind pr: the issue body whose criteria the checklist must cover",
    )
    parser.add_argument(
        "--epic",
        action="store_true",
        help="with --file --kind issue: the draft is an epic, which has no parent and no Owns",
    )
    parser.add_argument(
        "--comments", action="store_true", help="also check every comment on the PR"
    )
    parser.add_argument("--max-title", type=int, default=TITLE_LIMIT)
    parser.add_argument("--max-words", type=int, help="body budget; defaults by kind")
    parser.add_argument("--max-verification-lines", type=int, default=VERIFICATION_LINE_LIMIT)
    parser.add_argument("--max-acceptance-items", type=int, default=ACCEPTANCE_ITEM_LIMIT)
    parser.add_argument("--max-fenced-lines", type=int, default=FENCED_LINE_LIMIT)
    parser.add_argument("--max-chars", type=int, default=BODY_CHAR_LIMIT)
    parser.add_argument("--max-comment-words", type=int, default=REVIEW_WORD_LIMIT)
    parser.add_argument("--max-inline-words", type=int, default=COMMENT_WORD_LIMIT)
    arguments = parser.parse_args()
    if arguments.file is not None and arguments.kind is None:
        parser.error("--file needs --kind")
    if arguments.file is None and arguments.repo is None:
        parser.error("--issue and --pr need --repo")
    if arguments.comments and arguments.pr is None:
        parser.error("--comments needs --pr")
    if arguments.no_issue and arguments.closes is not None:
        parser.error("--no-issue and --closes contradict each other")
    if arguments.issue_body is not None and arguments.kind != "pr":
        parser.error("--issue-body goes with --file --kind pr")
    if arguments.epic and arguments.kind != "issue":
        parser.error("--epic goes with --file --kind issue")
    return arguments


def _limits(arguments: argparse.Namespace, kind: str) -> Limits:
    default_words = {
        "issue": ISSUE_WORD_LIMIT,
        "pr": PR_WORD_LIMIT,
        "comment": arguments.max_comment_words,
    }[kind]
    return Limits(
        title=arguments.max_title,
        words=arguments.max_words or default_words,
        verification_lines=arguments.max_verification_lines,
        fenced_lines=arguments.max_fenced_lines,
        chars=arguments.max_chars,
        acceptance_items=arguments.max_acceptance_items,
    )


def main() -> int:
    arguments = _parse_arguments()
    kind: str
    title: str | None
    body: str
    label: str
    draft = epic = False
    issue_body: str | None = None
    parent: Finding | None = None
    comments: list[tuple[str, str, str]] = []
    try:
        if arguments.file is not None:
            kind, title, label = arguments.kind, arguments.title, str(arguments.file)
            body = arguments.file.read_text(encoding="utf-8")
            epic = arguments.epic
            if arguments.issue_body is not None:
                issue_body = arguments.issue_body.read_text(encoding="utf-8")
            if kind == "issue":
                parent = Finding(
                    "WARN",
                    "issue.parent",
                    "not checked from a file; attach the parent after creation with "
                    "gh issue edit N --parent P",
                )
        elif arguments.issue is not None:
            kind, label = "issue", f"issue #{arguments.issue}"
            issue = _fetch_object(f"/repos/{arguments.repo}/issues/{arguments.issue}")
            title, body = str(issue.get("title", "")), str(issue.get("body") or "")
            epic = any(label_.get("name") == EPIC_LABEL for label_ in issue.get("labels", []))
            parent = check_parent(arguments.repo, arguments.issue, epic)
        else:
            kind, label = "pr", f"pull request #{arguments.pr}"
            pull = _fetch_object(f"/repos/{arguments.repo}/pulls/{arguments.pr}")
            title, body = str(pull.get("title", "")), str(pull.get("body") or "")
            draft = bool(pull.get("draft"))
            closed = arguments.closes or _closed_issue(body)
            if closed is not None and not arguments.no_issue:
                issue = _fetch_object(f"/repos/{arguments.repo}/issues/{closed}")
                issue_body = str(issue.get("body") or "")
            if arguments.comments:
                comments = _fetch_comments(arguments.repo, arguments.pr)
    except (check_ownership.GitHubError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    limits = _limits(arguments, kind)
    findings: list[Finding] = []
    if title is not None:
        findings.extend(check_title(title, limits.title))
    else:
        findings.append(Finding("WARN", "title.missing", "no --title given; title rules skipped"))
    findings.extend(
        check_body(
            kind,
            body,
            limits,
            draft=draft,
            closes=arguments.closes,
            no_issue=arguments.no_issue,
            issue_body=issue_body,
            epic=epic,
        )
    )
    if parent is not None:
        findings.append(parent)

    report = [_summary(label, title, body, kind), *_format(findings)]
    failed = sum(finding.level == "FAIL" for finding in findings)
    for comment_label, comment_kind, comment_body in comments:
        budget = (
            arguments.max_comment_words if comment_kind == "review" else arguments.max_inline_words
        )
        comment_findings = check_body("comment", comment_body, limits._replace(words=budget))
        failed += sum(finding.level == "FAIL" for finding in comment_findings)
        report.extend(["", f"--- {comment_label}", *_format(comment_findings)])

    # The verdict is settled before anything is printed, so a reader that closes the
    # pipe early cannot change the exit code, which is this tool's whole product.
    report.append("")
    if failed:
        report.append(f"{failed} checks failed. {VERDICTS[kind]}")
    else:
        report.append(f"All {len(findings)} checks passed.")
    check_ownership._print_tolerating_closed_pipe(report)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
