#!/usr/bin/env python3
"""Check an issue, pull request or comment against the programme's writing rules.

Everything the programme posts is read later by a person who was not there, so a
title, a body and every comment are held to the shape in references/WRITING.md: a
one-clause title without ticket ids, a body inside its word budget with verification
reported as one line per command, and nothing addressed to the agent or the reviewer as
a person. This reports every rule a writeup breaks and exits non-zero when there is at
least one. The supervisor runs it before dispatching an issue and before reading a pull
request; an agent runs it on a draft body before opening the pull request.

The text comes from GitHub (--issue or --pr, with a token in GH_TOKEN or GITHUB_TOKEN)
or from a local file (--file, which needs --kind). The budgets are the defaults
WRITING.md documents and move with the --max-* flags.
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Any, NamedTuple, cast

import check_ownership

TITLE_LIMIT = 72
ISSUE_WORD_LIMIT = 400
PR_WORD_LIMIT = 300
VERIFICATION_LINE_LIMIT = 12
FENCED_LINE_LIMIT = 20
BODY_CHAR_LIMIT = 10_000
REVIEW_WORD_LIMIT = 150
COMMENT_WORD_LIMIT = 60

TICKET_ID = re.compile(r"\bT-\d{3}\b")
FINDING_ID = re.compile(r"\b(?:CR|DP|EX|MG|OL|PN|QA|RF|RI)-\d{2}\b")
SERIES_PREFIX = re.compile(r"^[A-Z][A-Za-z]+ [A-Z0-9]{1,2}:\s")
FOOTER = re.compile(
    r"Generated by \[Claude Code\]|claude\.ai/code|session_[0-9A-Za-z]{16,}"
    r"|Co-Authored-By:|Claude-Session:",
    re.IGNORECASE,
)
CHECKBOX = re.compile(r"^\s*[-*] \[[ xX]\] ")
# A lone capital I followed by punctuation or a space, but not the I in I/O.
FIRST_PERSON = re.compile(r"(?<![\w/])I(?=[\s,.;:'!?]|$)")
SECOND_PERSON = re.compile(r"\b(?:you|your|yours)\b", re.IGNORECASE)
CLOSES = re.compile(r"\bCloses #(\d+)")
CLOSES_IN_CODE = re.compile(r"`[^`\n]*\bCloses #\d+[^`\n]*`")
CODE_SPAN = re.compile(r"`[^`\n]*`")
HEADING = re.compile(r"^#{1,6}\s+(.+?)\s*$")
LEAD_IN = re.compile(r"^\*\*([^*]+?)\*\*")
FENCE = re.compile(r"^(?:```|~~~)")
BULLET = re.compile(r"^\s*[-*] ")
DRAFT_FIRST_LINES = ("BLOCKED:", "DECISION REQUIRED:")

# Substrings that only ever appear when the writer is talking to the other agent, to
# itself, or about its tooling. Matched case-insensitively against every line.
BANNED_PHRASES = (
    "I want to be",
    "I was wrong",
    "I got wrong",
    "Correcting my",
    "Correcting the",
    "I said I would",
    "you caught",
    "beat my grep",
    "deserved better",
    "Nothing arrived outside",
    "Every acceptance criterion is met",
    "nothing outside Owns",
    "both granted paths are used",
    "Supervisor amendment",
    "as a finding rather than acted on",
    "Read this section before anything else",
    "yours to create",
    "pasted verbatim",
    "GraphQL is not served",
    "only the pinned set",
    "this session",
    "I cannot undraft",
)
# Section names, as a heading or a bold lead-in, that carry programme chatter rather
# than the work: rules repeated from the backlog, pasted output, or a confession.
BANNED_HEADINGS = (
    "Working agreement",
    "Verification block",
    "Files touched",
    "Note on how this work was directed",
    "Decisions where more than one option was defensible",
    "What was deliberately not done",
    "What I verified",
    "Two things I got wrong",
)
# Banned only as a bold lead-in: an epic body legitimately carries a Sequencing table,
# but a ticket that says "Sequencing." is publishing scheduler state as prose.
BANNED_LEAD_INS = ("Sequencing",)
EXCLUDED_SECTIONS = {"issue": ("owns", "must not touch"), "pr": ("verification",)}
VERDICTS = {
    "issue": "The issue goes back before it is dispatched.",
    "pr": "The writeup goes back before the diff is read.",
    "comment": "The comment is edited before it is posted.",
}


class Finding(NamedTuple):
    """One rule's result: `ok`, `WARN`, or `FAIL`, with what was measured."""

    level: str
    check: str
    detail: str


class Limits(NamedTuple):
    """The budgets one body is measured against."""

    title: int
    words: int
    verification_lines: int
    fenced_lines: int
    chars: int


class Segments(NamedTuple):
    """The parts of a body each rule reads, split once."""

    prose: list[tuple[int, str]]
    headings: list[tuple[int, str, bool]]
    fenced_lines: int
    verification_lines: int
    owns_has_details: bool


def segment(body: str, excluded: tuple[str, ...]) -> Segments:
    """Split a body into prose, headings and the counts the budgets need.

    Prose leaves out fenced blocks, `<details>` blocks, HTML comments, table rows and
    every line under a heading named in `excluded`, so a word count measures what a
    reader has to read. Headings carry whether they were a bold lead-in.
    """
    prose: list[tuple[int, str]] = []
    headings: list[tuple[int, str, bool]] = []
    fenced = verification = 0
    owns_has_details = False
    in_fence = in_details = in_comment = False
    section = ""
    for number, line in enumerate(body.splitlines(), start=1):
        stripped = line.strip()
        if in_comment:
            in_comment = "-->" not in stripped
            continue
        if stripped.startswith("<!--"):
            in_comment = "-->" not in stripped[4:]
            continue
        if FENCE.match(stripped):
            in_fence = not in_fence
            continue
        if in_fence:
            fenced += 0 if in_details else 1
            continue
        lowered = stripped.lower()
        if lowered.startswith("<details"):
            in_details = True
            owns_has_details = owns_has_details or section == "owns"
            continue
        if lowered.startswith("</details"):
            in_details = False
            continue
        if in_details:
            continue
        match = HEADING.match(stripped) or LEAD_IN.match(stripped)
        if match:
            text = match.group(1).strip().rstrip(".:")
            headings.append((number, text, not stripped.startswith("#")))
            section = text.lower()
            rest = stripped[match.end() :].strip()
            if rest and section not in excluded:
                prose.append((number, rest))
            continue
        if section == "verification" and BULLET.match(stripped):
            verification += 1
        if section in excluded or not stripped or stripped.startswith("|"):
            continue
        prose.append((number, line))
    return Segments(prose, headings, fenced, verification, owns_has_details)


def _verdict(
    check: str, passed: bool, detail: str, level: str = "FAIL", ok_detail: str | None = None
) -> Finding:
    if passed:
        return Finding("ok", check, detail if ok_detail is None else ok_detail)
    return Finding(level, check, detail)


def check_title(title: str, limit: int) -> list[Finding]:
    """Apply the title rules: one clause, under the cap, carrying no identifiers."""
    length = len(title)
    ticket = TICKET_ID.search(title)
    finding = FINDING_ID.search(title)
    series = SERIES_PREFIX.match(title)
    return [
        _verdict("title.length", length <= limit, f"{length} characters, limit {limit}"),
        _verdict("title.ticket-id", ticket is None, ticket.group(0) if ticket else "none"),
        _verdict("title.finding-id", finding is None, finding.group(0) if finding else "none"),
        _verdict(
            "title.series-prefix", series is None, series.group(0).strip() if series else "none"
        ),
        _verdict(
            "title.programme",
            "programme" not in title.lower(),
            "says 'programme'",
            ok_detail="no programme talk",
        ),
        _verdict(
            "title.trailing-period",
            not title.rstrip().endswith("."),
            "ends with a period",
            ok_detail="no trailing period",
        ),
    ]


def _word_count(prose: list[tuple[int, str]]) -> int:
    return sum(len(re.findall(r"\S+", text)) for _, text in prose)


def _line_hits(body: str, pattern: re.Pattern[str]) -> list[tuple[int, str]]:
    return [
        (number, match.group(0))
        for number, line in enumerate(body.splitlines(), start=1)
        if (match := pattern.search(line))
    ]


def _banned_phrases(body: str) -> list[Finding]:
    lines = body.lower().splitlines()
    hits = [
        (phrase, number)
        for phrase in BANNED_PHRASES
        for number, line in enumerate(lines, start=1)
        if phrase.lower() in line
    ]
    if not hits:
        return [Finding("ok", "body.banned", "no banned phrase")]
    return [
        Finding("FAIL", "body.banned", f'"{phrase}" (line {number})') for phrase, number in hits
    ]


def _banned_headings(headings: list[tuple[int, str, bool]]) -> list[Finding]:
    hits = []
    for number, text, is_lead_in in headings:
        lowered = text.lower()
        banned = [name for name in BANNED_HEADINGS if name.lower() in lowered]
        if is_lead_in:
            banned.extend(name for name in BANNED_LEAD_INS if lowered.startswith(name.lower()))
        hits.extend(f'"{text}" (line {number})' for _ in banned[:1])
    if not hits:
        return [Finding("ok", "body.banned-heading", "no banned section")]
    return [Finding("FAIL", "body.banned-heading", hit) for hit in hits]


def _footer(body: str) -> list[Finding]:
    hits = _line_hits(body, FOOTER)
    if not hits:
        return [Finding("ok", "body.footer", "no footer, session link or trailer")]
    return [Finding("FAIL", "body.footer", f"{text} (line {number})") for number, text in hits]


def _checkboxes(body: str) -> Finding:
    hits = _line_hits(body, CHECKBOX)
    if not hits:
        return Finding("ok", "body.checkbox", "no template checkbox")
    lines = ", ".join(str(number) for number, _ in hits[:5])
    return Finding("FAIL", "body.checkbox", f"{len(hits)} template checkboxes (lines {lines})")


def _non_ascii(body: str) -> Finding:
    for number, line in enumerate(body.splitlines(), start=1):
        if any(ord(character) > 127 for character in line):
            return Finding("FAIL", "body.non-ascii", f"line {number}: {line.strip()[:60]}")
    return Finding("ok", "body.non-ascii", "ASCII only")


def _person(prose: list[tuple[int, str]], pattern: re.Pattern[str]) -> int:
    return sum(
        len(pattern.findall(CODE_SPAN.sub(" ", text)))
        for _, text in prose
        if not text.lstrip().startswith(">")
    )


def _owns(body: str, parts: Segments) -> list[Finding]:
    findings = []
    try:
        patterns = check_ownership.owns_patterns_from_body(body, "this body")
    except check_ownership.GitHubError as error:
        findings.append(Finding("FAIL", "issue.owns", str(error)))
    else:
        findings.append(Finding("ok", "issue.owns", f"{len(patterns)} patterns parse"))
    if parts.owns_has_details:
        findings.append(Finding("FAIL", "issue.owns", "a <details> block inside the Owns section"))
    return findings


def _without_fences(body: str) -> str:
    kept = []
    in_fence = False
    for line in body.splitlines():
        if FENCE.match(line.strip()):
            in_fence = not in_fence
            continue
        if not in_fence:
            kept.append(line)
    return "\n".join(kept)


def _closes(body: str, expected: int | None) -> Finding:
    plain = CODE_SPAN.sub(" ", _without_fences(body))
    match = CLOSES.search(plain)
    if match is None and CLOSES_IN_CODE.search(body):
        return Finding("FAIL", "pr.closes", "Closes #N is inside a code span, which GitHub ignores")
    if match is None:
        return Finding("FAIL", "pr.closes", "no Closes #N line")
    number = int(match.group(1))
    if expected is not None and number != expected:
        return Finding("FAIL", "pr.closes", f"Closes #{number}, expected #{expected}")
    return Finding("ok", "pr.closes", f"Closes #{number} is a live closing keyword")


def check_body(
    kind: str,
    body: str,
    limits: Limits,
    *,
    draft: bool = False,
    closes: int | None = None,
) -> list[Finding]:
    """Apply every body rule for `kind` (issue, pr or comment) and return the findings."""
    parts = segment(body, EXCLUDED_SECTIONS.get(kind, ()))
    words = _word_count(parts.prose)
    findings = [
        _verdict("body.words", words <= limits.words, f"{words} words, limit {limits.words}"),
        _verdict(
            "body.fenced-lines",
            parts.fenced_lines <= limits.fenced_lines,
            f"{parts.fenced_lines} outside <details>, limit {limits.fenced_lines}",
        ),
        _verdict("body.chars", len(body) <= limits.chars, f"{len(body)}, limit {limits.chars}"),
        *_banned_phrases(body),
        *_banned_headings(parts.headings),
        *_footer(body),
        _checkboxes(body),
        _non_ascii(body),
    ]
    first_person = _person(parts.prose, FIRST_PERSON)
    findings.append(
        _verdict(
            "body.first-person",
            first_person == 0,
            f"{first_person} first-person sentences",
            level="WARN" if kind == "comment" else "FAIL",
        )
    )
    if kind == "issue":
        second_person = _person(parts.prose, SECOND_PERSON)
        findings.append(
            _verdict("issue.second-person", second_person == 0, f"{second_person} addresses")
        )
        findings.extend(_owns(body, parts))
    if kind == "pr":
        findings.append(_closes(body, closes))
        has_verification = any(text.lower() == "verification" for _, text, _ in parts.headings)
        findings.append(
            _verdict(
                "pr.verification",
                has_verification,
                "no ## Verification section",
                ok_detail="a Verification section is present",
            )
        )
        if has_verification:
            findings.append(
                _verdict(
                    "pr.verification",
                    parts.verification_lines <= limits.verification_lines,
                    f"{parts.verification_lines} lines, limit {limits.verification_lines}",
                )
            )
        has_not_done = any(text.lower() == "not done" for _, text, _ in parts.headings)
        findings.append(
            _verdict(
                "pr.not-done",
                has_not_done,
                "no ## Not done section",
                ok_detail="a Not done section is present",
            )
        )
        if draft:
            first = next((line for line in body.splitlines() if line.strip()), "")
            findings.append(
                _verdict(
                    "pr.draft",
                    first.startswith(DRAFT_FIRST_LINES),
                    "a draft that does not open with BLOCKED: or DECISION REQUIRED:",
                    level="WARN",
                    ok_detail="the draft opens with its protocol line",
                )
            )
    return findings


def _summary(label: str, title: str | None, body: str, kind: str) -> str:
    parts = segment(body, EXCLUDED_SECTIONS.get(kind, ()))
    title_part = f"title {len(title)} chars" if title is not None else "no title given"
    return (
        f"writeup ({label}): {title_part}; body {len(body)} chars, "
        f"{_word_count(parts.prose)} words, {parts.fenced_lines} fenced lines"
    )


def _fetch_object(path: str) -> dict[str, Any]:
    """GET one JSON object, refusing anything else."""
    payload = check_ownership._get(path)
    if not isinstance(payload, dict):
        raise check_ownership.GitHubError(f"unexpected response from GET {path}")
    return cast("dict[str, Any]", payload)


def _fetch_list(path: str) -> list[dict[str, Any]]:
    """GET one JSON list of objects, refusing anything else."""
    payload = check_ownership._get(path)
    if not isinstance(payload, list):
        raise check_ownership.GitHubError(f"unexpected response from GET {path}")
    return cast("list[dict[str, Any]]", payload)


def _fetch_comments(repo: str, pull_number: int) -> list[tuple[str, str, str]]:
    """Return (label, kind, body) for every comment on the pull request not left by a bot."""
    sources = (
        ("review", f"/repos/{repo}/pulls/{pull_number}/reviews"),
        ("inline", f"/repos/{repo}/pulls/{pull_number}/comments"),
        ("comment", f"/repos/{repo}/issues/{pull_number}/comments"),
    )
    comments: list[tuple[str, str, str]] = []
    for kind, path in sources:
        for entry in _fetch_list(f"{path}?per_page=100"):
            author = str(entry.get("user", {}).get("login", ""))
            body = entry.get("body")
            if author.endswith("[bot]") or not body:
                continue
            comments.append((f"{kind} {entry.get('id')} by {author}", kind, str(body)))
    return comments


def _format(findings: list[Finding]) -> list[str]:
    return [f"{finding.level:<4}  {finding.check:<22}{finding.detail}" for finding in findings]


def _parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--issue", type=int, metavar="N", help="check issue N on --repo")
    source.add_argument("--pr", type=int, metavar="N", help="check pull request N on --repo")
    source.add_argument("--file", type=Path, metavar="BODY.md", help="check a body on disk")
    parser.add_argument("--repo", metavar="OWNER/REPO")
    parser.add_argument("--kind", choices=("issue", "pr", "comment"), help="required with --file")
    parser.add_argument("--title", help="the title to check alongside --file")
    parser.add_argument("--closes", type=int, metavar="M", help="the issue a PR must close")
    parser.add_argument(
        "--comments", action="store_true", help="also check every comment on the PR"
    )
    parser.add_argument("--max-title", type=int, default=TITLE_LIMIT)
    parser.add_argument("--max-words", type=int, help="body budget; defaults by kind")
    parser.add_argument("--max-verification-lines", type=int, default=VERIFICATION_LINE_LIMIT)
    parser.add_argument("--max-fenced-lines", type=int, default=FENCED_LINE_LIMIT)
    parser.add_argument("--max-chars", type=int, default=BODY_CHAR_LIMIT)
    parser.add_argument("--max-comment-words", type=int, default=REVIEW_WORD_LIMIT)
    parser.add_argument("--max-inline-words", type=int, default=COMMENT_WORD_LIMIT)
    arguments = parser.parse_args()
    if arguments.file is not None and arguments.kind is None:
        parser.error("--file needs --kind")
    if arguments.file is None and arguments.repo is None:
        parser.error("--issue and --pr need --repo")
    if arguments.comments and arguments.pr is None:
        parser.error("--comments needs --pr")
    return arguments


def _limits(arguments: argparse.Namespace, kind: str) -> Limits:
    default_words = {
        "issue": ISSUE_WORD_LIMIT,
        "pr": PR_WORD_LIMIT,
        "comment": arguments.max_comment_words,
    }[kind]
    return Limits(
        title=arguments.max_title,
        words=arguments.max_words or default_words,
        verification_lines=arguments.max_verification_lines,
        fenced_lines=arguments.max_fenced_lines,
        chars=arguments.max_chars,
    )


def main() -> int:
    arguments = _parse_arguments()
    kind: str
    title: str | None
    body: str
    label: str
    draft = False
    comments: list[tuple[str, str, str]] = []
    try:
        if arguments.file is not None:
            kind, title, label = arguments.kind, arguments.title, str(arguments.file)
            body = arguments.file.read_text(encoding="utf-8")
        elif arguments.issue is not None:
            kind, label = "issue", f"issue #{arguments.issue}"
            issue = _fetch_object(f"/repos/{arguments.repo}/issues/{arguments.issue}")
            title, body = str(issue.get("title", "")), str(issue.get("body") or "")
        else:
            kind, label = "pr", f"pull request #{arguments.pr}"
            pull = _fetch_object(f"/repos/{arguments.repo}/pulls/{arguments.pr}")
            title, body = str(pull.get("title", "")), str(pull.get("body") or "")
            draft = bool(pull.get("draft"))
            if arguments.comments:
                comments = _fetch_comments(arguments.repo, arguments.pr)
    except (check_ownership.GitHubError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    limits = _limits(arguments, kind)
    findings: list[Finding] = []
    if title is not None:
        findings.extend(check_title(title, limits.title))
    else:
        findings.append(Finding("WARN", "title.missing", "no --title given; title rules skipped"))
    findings.extend(check_body(kind, body, limits, draft=draft, closes=arguments.closes))

    report = [_summary(label, title, body, kind), *_format(findings)]
    failed = sum(finding.level == "FAIL" for finding in findings)
    for comment_label, comment_kind, comment_body in comments:
        budget = (
            arguments.max_comment_words if comment_kind == "review" else arguments.max_inline_words
        )
        comment_findings = check_body("comment", comment_body, limits._replace(words=budget))
        failed += sum(finding.level == "FAIL" for finding in comment_findings)
        report.extend(["", f"--- {comment_label}", *_format(comment_findings)])

    # The verdict is settled before anything is printed, so a reader that closes the
    # pipe early cannot change the exit code, which is this tool's whole product.
    report.append("")
    if failed:
        report.append(f"{failed} checks failed. {VERDICTS[kind]}")
    else:
        report.append(f"All {len(findings)} checks passed.")
    check_ownership._print_tolerating_closed_pipe(report)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
