"""Unit tests for the writeup check that gates what the programme posts to GitHub."""

from __future__ import annotations

import sys
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest

SCRIPTS = (
    Path(__file__).resolve().parents[2] / ".agents" / "skills" / "bustan-supervisor" / "scripts"
)

SKELETON_ISSUE = """Refs T-500

## Context
The pipeline is resolved again on every request because the plan is rebuilt from the
module graph each time the runtime enters a route.

## Change
Memoize the resolved pipeline per route at bootstrap and reuse it per request.

## Acceptance
- One resolution per route across the suite.
- PN-11 reports FIXED.

## Owns
- `src/bustan/runtime/execution.py`
- `src/bustan/kernel/ioc/runtime/` (new)

## Must not touch
- `src/bustan/kernel/ioc/planning/`

## Delivery
Branch `feat/t-500-pipeline-memoization` from `main`.
"""

DETAILS_ISSUE = """## Owns
<details><summary>paths</summary>

- `src/bustan/runtime/execution.py`

</details>
Run `main` and `pytest` first.

## Must not touch
- `src/bustan/kernel/`
"""

CLEAN_PR = """Closes #241
Refs T-502, DP-01, DP-02

## What changed
The body binder now checks each field against its declared type before the handler
runs, so a string in an integer field is a 422 with the field named rather than a
500 from inside the handler.

## Verification
- `uv run ruff format --check . && uv run ruff check .`: All checks passed
- `uv run pytest --cov=bustan --cov-report=term-missing`: 1187 passed; TOTAL 96%
- `uv run python docs/audits/di-container-2026-09/run_repros.py`: DP-01, DP-02 FIXED

## Decisions
- Unexpected keys are reported by name: a silent drop hides a client typo.

## Not done
- Nothing in scope was left undone.
"""

PASTED_PR = "\n".join(
    [
        "## Summary",
        "I fixed the binding so that every acceptance criterion is met.",
        "",
        "### Note on how this work was directed",
        "Nothing arrived outside this pull request.",
        "",
        "## Validation",
        "- [x] `uv run ruff check .`",
        "",
        "## Verification block, pasted verbatim",
        "```",
        *(f"tests/unit/test_{index}.py ....  [ {index}%]" for index in range(30)),
        "```",
        "",
        "`Closes #241`",
        "",
        "_Generated by [Claude Code](https://claude.ai/code/session_017U4hwsLm8tE9WVXogSo8vr)_",
    ]
)


def _load(name: str) -> ModuleType:
    if name in sys.modules:
        return sys.modules[name]
    module_spec = spec_from_file_location(name, SCRIPTS / f"{name}.py")
    assert module_spec is not None
    assert module_spec.loader is not None
    module = module_from_spec(module_spec)
    # Registered before execution so check_writeup's own `import check_ownership`
    # resolves to the copy loaded here rather than searching sys.path for one.
    sys.modules[name] = module
    module_spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def writeup() -> ModuleType:
    _load("check_ownership")
    return _load("check_writeup")


def _failing(findings: list[Any]) -> set[str]:
    return {finding.check for finding in findings if finding.level == "FAIL"}


def test_the_ownership_parser_reads_the_issue_skeleton(writeup: ModuleType) -> None:
    ownership = writeup.check_ownership

    patterns = ownership.owns_patterns_from_body(SKELETON_ISSUE, "the skeleton")

    assert patterns == ["src/bustan/runtime/execution.py", "src/bustan/kernel/ioc/runtime/"]


def test_the_ownership_parser_refuses_prose_after_a_details_wrapper(
    writeup: ModuleType,
) -> None:
    ownership = writeup.check_ownership

    with pytest.raises(ownership.GitHubError, match="main, pytest"):
        ownership.owns_patterns_from_body(DETAILS_ISSUE, "the wrapped body")


def test_a_skeleton_issue_passes(writeup: ModuleType) -> None:
    limits = writeup.Limits(
        title=72, words=400, verification_lines=12, fenced_lines=20, chars=10_000
    )

    findings = writeup.check_title("Memoize the resolved pipeline per route", 72)
    findings += writeup.check_body("issue", SKELETON_ISSUE, limits)

    assert _failing(findings) == set()


def test_an_issue_that_addresses_the_agent_fails(writeup: ModuleType) -> None:
    limits = writeup.Limits(
        title=72, words=400, verification_lines=12, fenced_lines=20, chars=10_000
    )
    body = SKELETON_ISSUE.replace(
        "Memoize the resolved pipeline", "Grep your own branch, then memoize the pipeline"
    )

    findings = writeup.check_body("issue", body, limits)

    assert _failing(findings) == {"issue.second-person"}


def test_a_clean_pull_request_body_passes(writeup: ModuleType) -> None:
    limits = writeup.Limits(
        title=72, words=300, verification_lines=12, fenced_lines=20, chars=10_000
    )

    findings = writeup.check_title("fix(runtime): bind body fields to their declared types", 72)
    findings += writeup.check_body("pr", CLEAN_PR, limits, closes=241)

    assert _failing(findings) == set()


def test_a_pasted_transcript_body_fails_on_each_rule_it_breaks(writeup: ModuleType) -> None:
    limits = writeup.Limits(
        title=72, words=300, verification_lines=12, fenced_lines=20, chars=10_000
    )

    findings = writeup.check_title("fix(kernel): T-502 NestJS parity gaps (DP-01, DP-02)", 72)
    findings += writeup.check_body("pr", PASTED_PR, limits, closes=241)

    assert _failing(findings) == {
        "title.ticket-id",
        "title.finding-id",
        "body.fenced-lines",
        "body.banned",
        "body.banned-heading",
        "body.footer",
        "body.checkbox",
        "body.first-person",
        "pr.closes",
        "pr.verification",
        "pr.not-done",
    }


def test_a_pull_request_that_closes_no_issue_can_say_so(writeup: ModuleType) -> None:
    limits = writeup.Limits(
        title=72, words=300, verification_lines=12, fenced_lines=20, chars=10_000
    )
    body = CLEAN_PR.replace("Closes #241\n", "")

    assert "pr.closes" in _failing(writeup.check_body("pr", body, limits))
    assert "pr.closes" not in _failing(writeup.check_body("pr", body, limits, no_issue=True))


def test_closes_inside_a_code_span_is_named_as_the_reason(writeup: ModuleType) -> None:
    finding = writeup._closes("Summary.\n\n`Closes #12`\n", None)

    assert finding.level == "FAIL"
    assert "code span" in finding.detail


def test_the_word_budget_leaves_out_fences_tables_and_owned_lists(writeup: ModuleType) -> None:
    limits = writeup.Limits(
        title=72, words=100, verification_lines=12, fenced_lines=500, chars=100_000
    )
    filler = " ".join(["word"] * 400)
    body = SKELETON_ISSUE + "\n## Notes\n```\n" + filler + "\n```\n| " + filler + " |\n"

    findings = writeup.check_body("issue", body, limits)

    assert "body.words" not in _failing(findings)


@pytest.mark.parametrize(
    ("title", "expected"),
    [
        ("Layering A: the kernel reads controller metadata", {"title.series-prefix"}),
        ("Two per-request allocations survive T-500", {"title.ticket-id"}),
        (
            "Nobody in this programme can establish whether a red build blocks a merge",
            {"title.programme", "title.length"},
        ),
        ("Finish the body-binding messages.", {"title.trailing-period"}),
        ("fix(kernel): reject a request-scoped provider in a singleton", set()),
    ],
)
def test_title_rules(writeup: ModuleType, title: str, expected: set[str]) -> None:
    assert _failing(writeup.check_title(title, 72)) == expected
